baseurl: /

collections:
  coffee:
    output: true
    permalink: /:title

sass:
  load_paths:
    - _sass
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

exclude:
  - node_modules

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
