baseurl: /personal-page

collections:
  coffee:
    output: true
    permalink: /:title

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
